[project]
name = "cli"
description = "Create command line interfaces in Python."
version = "0.0.1"

readme = "README.md"
license = "GPL-2.0"
license-files = ["LICEN[CS]E*"]

classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]

requires-python = ">= 3.14"
dependencies = []

[[project.authors]]
name = "Philipp Kosarev"
email = "philipp.kosarev@gmail.com"

[project.urls]
homepage = "https://github.com/philippkosarev/cli"
source = "https://github.com/philippkosarev/cli"
issues = "https://github.com/philippkosarev/cli/issues"
documentation = "https://cli.readthedocs.io"

[dependency-groups]
docs = [
  "sphinx >= 8.2, < 9",
  "sphinx-toolbox >= 4.1.2, < 5",
  "pydata-sphinx-theme",
  "sphinx-copybutton",
  "pypandoc",
  "pypandoc-binary",
  "sphinxcontrib-programoutput",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
include = ["cli"]
